#
# Server Properties
#
server:
  port: 8080
  tomcat:
    accept-count: 100

service:
  flight-schedule:
    max-wind: 30
    min-visibility: 200
    positive-message: по расписанию
    negative-message: отменен
